"use client";
import { useState, useEffect } from "react";
import { BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";
import * as Shared from "./shared";
const { C,MON,WEEKDAYS,MOODS,getCurWeek,Card,Lbl,Chip,Confetti,Skel,DrillBlock } = Shared;
export function DashTab({habits,goals,txs,projects,journal,wallets,recurring,loans,TD,TM,WS,sh,sg,income,expense,balance,doneToday,todayGoals,wGoals,setTab,briefing,loadingBriefing,refreshBriefing,widgets,setWidgets}){
  const h=new Date().getHours();const greeting=h<5?"Доброй ночи":h<12?"Доброе утро":h<18?"Добрый день":"Добрый вечер";
  const hScore=habits.length?Math.round(doneToday/habits.length*40):0;const gScore=todayGoals.length?Math.round(todayGoals.filter(g=>g.done).length/todayGoals.length*30):30;const bScore=income>0?(expense<=income?30:Math.max(0,30-Math.round((expense-income)/income*30))):15;const score=Math.min(100,hScore+gScore+bScore);const scoreColor=score>=80?C.green:score>=55?C.cyan:score>=35?C.amber:C.red;const pct=habits.length?Math.round(doneToday/habits.length*100):0;const mood=MOODS.find(m=>m.v===journal.find(j=>j.date===TD)?.mood);
  const[confetti,setConfetti]=useState(false);const[prevDone,setPrevDone]=useState(0);useEffect(()=>{if(habits.length>0&&doneToday===habits.length&&prevDone<habits.length&&!confetti)setConfetti(true);setPrevDone(doneToday)},[doneToday,habits.length]);
  const[editWidgets,setEditWidgets]=useState(false);const toggleW=k=>setWidgets(prev=>({...prev,[k]:!prev[k]}));
  const[calDate,setCalDate]=useState(new Date());const[selDay,setSelDay]=useState(TD);const[showMonth,setShowMonth]=useState(false);const weekDays=getCurWeek();
  const dayData=ds=>{const dGoals=goals.daily.filter(g=>g.date===ds),dTxs=txs.filter(t=>t.date===ds&&t.status!=="pending"),dPend=txs.filter(t=>t.chargeDate===ds&&t.status==="pending"),dHab=habits.filter(hh=>hh.done[ds]),dayNum=parseInt(ds.split("-")[2]),month=ds.slice(0,7),dRec=recurring.filter(r=>r.active&&r.dayOfMonth===dayNum&&ds.startsWith(month)),dLoans=loans.filter(l=>l.active&&l.dayOfMonth===dayNum&&ds.startsWith(month));return{dGoals,dTxs,dPend,dHab,dRec,dLoans}};
  const yr=calDate.getFullYear(),mo=calDate.getMonth(),firstDow=new Date(yr,mo,1).getDay(),offset=firstDow===0?6:firstDow-1,daysInMonth=new Date(yr,mo+1,0).getDate(),cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let d=1;d<=daysInMonth;d++)cells.push(`${yr}-${String(mo+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`);
  const sd=dayData(selDay),selInc=sd.dTxs.filter(t=>t.type==="income").reduce((a,b)=>a+b.amount,0),selExp=sd.dTxs.filter(t=>t.type==="expense").reduce((a,b)=>a+b.amount,0);
  const last14=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);const date=d.toISOString().split("T")[0],done=habits.filter(hh=>hh.done[date]).length;return{day:d.getDate(),pct:habits.length?Math.round(done/habits.length*100):0,isT:date===TD}});
  const last6=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,mt=txs.filter(t=>t.date.startsWith(m)&&t.status!=="pending");return{label:MON[d.getMonth()],Доход:mt.filter(t=>t.type==="income").reduce((a,b)=>a+b.amount,0),Расход:mt.filter(t=>t.type==="expense").reduce((a,b)=>a+b.amount,0)}});
  const Tip=({active,payload,label})=>!active||!payload?.length?null:<div style={{background:C.card2,border:`1px solid ${C.border}`,borderRadius:8,padding:"6px 10px",fontSize:10}}><div style={{color:C.muted}}>{label}</div>{payload.map((p,i)=><div key={i} style={{color:p.color}}>{p.name}: {p.value>99?`₪${p.value.toLocaleString()}`:p.value+"%"}</div>)}</div>;
  const Dots=({ds})=>{const{dGoals,dTxs,dPend,dHab,dRec,dLoans}=dayData(ds);return <div style={{display:"flex",justifyContent:"center",gap:2,minHeight:6}}>{dGoals.length>0&&<i style={{width:4,height:4,borderRadius:"50%",background:C.purple}}/>}{dTxs.length>0&&<i style={{width:4,height:4,borderRadius:"50%",background:C.green}}/>}{dHab.length>0&&<i style={{width:4,height:4,borderRadius:"50%",background:C.cyan}}/>}{dPend.length>0&&<i style={{width:4,height:4,borderRadius:"50%",background:C.amber}}/>}{(dRec.length>0||dLoans.length>0)&&<i style={{width:4,height:4,borderRadius:"50%",background:C.red}}/>}</div>};
  const WIDGET_LABELS={briefing:"🤖 AI Briefing",habits:"✅ Привычки",goals:"🎯 Цели дня",calendar:"📅 Календарь",analytics:"📊 Аналитика",finance:"💰 Финансы"};
  return <div style={{padding:16,display:"flex",flexDirection:"column",gap:12}} className="fu">{confetti&&<Confetti onDone={()=>setConfetti(false)}/>}<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"4px 0"}}><div><div style={{fontSize:10,color:C.muted}}>{greeting},</div><div style={{fontSize:22,fontWeight:800}}>Алексей {mood?.e||"👋"}</div></div><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={()=>setEditWidgets(!editWidgets)} style={{background:editWidgets?"rgba(0,212,255,.08)":"transparent",border:`1px solid ${editWidgets?C.cyan:C.border}`,color:editWidgets?C.cyan:C.muted,borderRadius:7,padding:"4px 9px",fontSize:11}}>⚙ Виджеты</button><div style={{position:"relative",width:50,height:50}}><svg viewBox="0 0 50 50" style={{transform:"rotate(-90deg)",width:50,height:50}}><circle cx="25" cy="25" r="19" fill="none" stroke={C.dim} strokeWidth="4"/><circle cx="25" cy="25" r="19" fill="none" stroke={scoreColor} strokeWidth="4" strokeDasharray={`${2*Math.PI*19}`} strokeDashoffset={`${2*Math.PI*19*(1-score/100)}`} strokeLinecap="round"/></svg><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:scoreColor}}>{score}</div></div></div></div>
  {editWidgets&&<Card glow s={{padding:12}}><Lbl>Управление виджетами</Lbl><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{Object.entries(WIDGET_LABELS).map(([k,l])=><Chip key={k} active={widgets[k]} onClick={()=>toggleW(k)}>{l} {widgets[k]?"✓":"○"}</Chip>)}</div></Card>}
  {widgets.briefing&&<div style={{background:"linear-gradient(135deg,rgba(0,68,187,.12),rgba(0,212,255,.05))",borderRadius:12,border:"1px solid rgba(0,212,255,.18)",padding:"12px 14px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:7}}><span style={{fontSize:9,fontWeight:800,letterSpacing:2,color:C.cyan}}>NEXUS BRIEFING</span><button onClick={refreshBriefing} disabled={loadingBriefing} style={{background:"transparent",border:`1px solid ${C.border}`,color:C.muted,borderRadius:5,padding:"2px 8px",fontSize:9}}>{loadingBriefing?"⟳":"↻ обновить"}</button></div>{loadingBriefing?<div><Skel h={10}/><Skel w="80%" h={10}/></div>:<div style={{fontSize:12,lineHeight:1.65,whiteSpace:"pre-wrap"}}>{briefing||"Нажми ↻ для утренней сводки"}</div>}</div>}
  <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{widgets.habits&&<DrillBlock icon="✅" label="Привычки" value={`${doneToday}/${habits.length}`} sub={`${pct}%`} color={pct===100?C.green:C.cyan} onClick={()=>setTab("habits")}/>}<DrillBlock icon="🗂" label="Фокус" value={`${todayGoals.filter(g=>g.done).length}/${todayGoals.length}`} sub="цели дня" color={C.purple} onClick={()=>setTab("life")}/><DrillBlock icon="📈" label="Аналитика" value={String(score)} sub="Score" color={scoreColor} onClick={()=>setTab("analytics")}/></div>
  {widgets.calendar&&<Card s={{padding:"13px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><Lbl>📅 Календарь</Lbl><button onClick={()=>setShowMonth(!showMonth)} style={{background:"transparent",border:`1px solid ${C.border}`,color:C.muted,borderRadius:6,padding:"3px 9px",fontSize:9}}>{showMonth?"Неделя ↑":"Месяц ↓"}</button></div>{!showMonth?<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,marginBottom:10}}>{weekDays.map((day,i)=>{const isT=day===TD,isSel=day===selDay;return <div key={day} onClick={()=>setSelDay(day)} style={{borderRadius:7,padding:"5px 2px",textAlign:"center",border:`1px solid ${isSel?C.cyan:"transparent"}`,background:isSel?"rgba(0,212,255,.08)":"transparent"}}><div style={{fontSize:8,color:isT?C.cyan:C.muted}}>{WEEKDAYS[i]}</div><div style={{fontSize:12,color:isT?C.cyan:C.text}}>{parseInt(day.split("-")[2])}</div><Dots ds={day}/></div>})}</div>:<div><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><button onClick={()=>{const d=new Date(calDate);d.setMonth(d.getMonth()-1);setCalDate(d)}}>←</button><span>{MON[mo]} {yr}</span><button onClick={()=>{const d=new Date(calDate);d.setMonth(d.getMonth()+1);setCalDate(d)}}>→</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:2}}>{cells.map((ds,i)=>!ds?<div key={i}/>:<div key={ds} onClick={()=>setSelDay(ds)} style={{borderRadius:5,padding:3,textAlign:"center",border:`1px solid ${ds===selDay?C.cyan:"transparent"}`}}><div style={{fontSize:9}}>{parseInt(ds.split("-")[2])}</div><Dots ds={ds}/></div>)}</div></div>}<div style={{borderTop:`1px solid ${C.border}`,paddingTop:9}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:7}}><b style={{fontSize:11}}>{new Date(selDay+"T12:00:00").toLocaleDateString("ru-RU",{weekday:"short",day:"numeric",month:"short"})}</b><span style={{fontSize:10}}>{selInc>0&&<i style={{color:C.green}}>+₪{selInc} </i>}{selExp>0&&<i style={{color:C.red}}>-₪{selExp}</i>}</span></div>{sd.dGoals.map(g=><div key={g.id} style={{fontSize:11}}>{g.done?"✅":"⬜"} {g.text}</div>)}{sd.dTxs.map(t=><div key={t.id} style={{display:"flex",justifyContent:"space-between",fontSize:11}}><span>{t.description}</span><span style={{color:t.type==="income"?C.green:C.red}}>{t.type==="income"?"+":"-"}₪{t.amount}</span></div>)}</div></Card>}
  {widgets.analytics&&<Card onClick={()=>setTab("analytics")}><div style={{display:"flex",justifyContent:"space-between"}}><Lbl>📊 Аналитика</Lbl><span style={{fontSize:10,color:C.cyan}}>Детально →</span></div><ResponsiveContainer width="100%" height={48}><BarChart data={last14}><XAxis dataKey="day" tick={{fill:C.muted,fontSize:7}} axisLine={false}/><Tooltip content={<Tip/>}/><Bar dataKey="pct">{last14.map((e,i)=><Cell key={i} fill={e.pct===100?C.green:e.pct>=50?C.cyan:C.dim}/>)}</Bar></BarChart></ResponsiveContainer><ResponsiveContainer width="100%" height={48}><BarChart data={last6}><XAxis dataKey="label" tick={{fill:C.muted,fontSize:7}} axisLine={false}/><Bar dataKey="Доход" fill={C.green}/><Bar dataKey="Расход" fill={C.red}/></BarChart></ResponsiveContainer></Card>}
  {widgets.finance&&<Card onClick={()=>setTab("finance")}><div style={{display:"flex",justifyContent:"space-between"}}><div><Lbl color={C.muted}>💰 Финансы {MON[new Date().getMonth()]}</Lbl><div style={{fontSize:22,fontWeight:900,color:balance>=0?C.green:C.red}}>{balance>=0?"+":"-"}₪{Math.abs(balance).toLocaleString()}</div><div style={{fontSize:10}}><span style={{color:C.green}}>+₪{income.toLocaleString()}</span> · <span style={{color:C.red}}>-₪{expense.toLocaleString()}</span></div></div><span style={{color:C.cyan}}>→</span></div></Card>}
  </div>;
}
