"use client";
import { useState, useEffect, useRef, useCallback } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";
export { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell };

export const THEMES=[
  {id:"nexus",name:"NEXUS",hue:0,icon:"🔵"},{id:"amethyst",name:"Amethyst",hue:90,icon:"🟣"},{id:"crimson",name:"Crimson",hue:180,icon:"🔴"},{id:"matrix",name:"Matrix",hue:-90,icon:"🟢"},{id:"sapphire",name:"Sapphire",hue:40,icon:"💙"},
];
export const C={bg:"#050a14",card:"#080e1c",card2:"#0c1525",border:"rgba(0,212,255,0.1)",hi:"rgba(0,212,255,0.4)",cyan:"#00d4ff",purple:"#7c3aed",green:"#10b981",amber:"#f59e0b",red:"#ef4444",pink:"#ec4899",blue:"#3b82f6",text:"#c8d8e8",muted:"#4e6687",dim:"#1a2d45"};
export const MON=["янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек"];
export const WEEKDAYS=["пн","вт","ср","чт","пт","сб","вс"];
export const EXP_CATS=["🍔 Еда","🚗 Транспорт","🏥 Здоровье","🎬 Развлечения","👕 Одежда","🏠 Жильё","📱 Подписки","💡 Коммуналки","🛒 Покупки","❓ Другое"];
export const INC_CATS=["💼 Зарплата","💻 Фриланс","📈 Инвестиции","🎁 Подарки","❓ Другое"];
export const MOODS=[{v:1,e:"😞",l:"Тяжело"},{v:2,e:"😐",l:"Нейтрально"},{v:3,e:"😊",l:"Хорошо"},{v:4,e:"😄",l:"Отлично"},{v:5,e:"🤩",l:"Великолепно"}];
export const ICONS=["💧","🏃","📖","🧘","💊","🍎","😴","🏋️","✍️","🎯","💻","🧴","☕","🚶","🎵","🌿","🔥","⚡","🧠","❤️"];
export const HCOLS=[C.cyan,C.green,C.purple,C.amber,C.red,C.pink,"#06b6d4","#8b5cf6"];
export const PROJ_ICONS=["📁","🚀","💡","🎯","🔧","📱","🏗️","✨","🎨","📊"];
export const PROJ_COLORS=[C.cyan,C.green,C.purple,C.amber,C.red,C.pink,"#3b82f6","#06b6d4"];
export const CAT_MAP={"Еда":"🍔 Еда","Транспорт":"🚗 Транспорт","Здоровье":"🏥 Здоровье","Развлечения":"🎬 Развлечения","Одежда":"👕 Одежда","Жильё":"🏠 Жильё","Подписки":"📱 Подписки","Коммуналки":"💡 Коммуналки","Покупки":"🛒 Покупки","Зарплата":"💼 Зарплата","Фриланс":"💻 Фриланс","Инвестиции":"📈 Инвестиции","Подарки":"🎁 Подарки","Другое":"❓ Другое","Кредит":"🏦 Кредит"};
export const DEF_WALLETS=[{id:"w1",name:"Наличка",type:"cash",icon:"💵",color:C.green},{id:"w2",name:"Банк. карта",type:"bank",icon:"🏦",color:C.cyan,feePercent:0},{id:"w3",name:"Кредитная",type:"credit",icon:"💳",color:C.purple,billingDay:10,feePercent:0,linkedWalletId:"w2"}];
export const CRYPTO_MAP={'BTC':'bitcoin','ETH':'ethereum','SOL':'solana','BNB':'binancecoin','ADA':'cardano','XRP':'ripple','DOT':'polkadot','AVAX':'avalanche-2','MATIC':'matic-network','LINK':'chainlink','UNI':'uniswap','DOGE':'dogecoin','SHIB':'shiba-inu','LTC':'litecoin','ATOM':'cosmos','USDT':'tether','USDC':'usd-coin','TRX':'tron','TON':'the-open-network','NEAR':'near','PEPE':'pepe'};
export const DEF_WIDGETS={briefing:true,habits:true,goals:true,calendar:true,analytics:true,finance:true};
export const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
export const getToday=()=>new Date().toISOString().split("T")[0];
export const getMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;};
export const getWeekStart=()=>{const d=new Date(),day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d.toISOString().split("T")[0];};
export const getCurWeek=()=>{const today=new Date(),dow=today.getDay();const mon=new Date(today);mon.setDate(today.getDate()-(dow===0?6:dow-1));return Array.from({length:7},(_,i)=>{const d=new Date(mon);d.setDate(mon.getDate()+i);return d.toISOString().split("T")[0];});};
export const getBillDate=(bd,n=1)=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth()+n,bd).toISOString().split("T")[0];};
export const fmtDate=(s)=>{if(!s)return"";const d=new Date(s+"T12:00:00");return `${d.getDate()} ${MON[d.getMonth()]}`;};
export const db={get:async(k,fb)=>{try{if(typeof window==="undefined")return fb;const raw=window.localStorage.getItem(k);return raw?JSON.parse(raw):fb;}catch{return fb;}},set:async(k,v)=>{try{if(typeof window!=="undefined")window.localStorage.setItem(k,JSON.stringify(v));}catch{}}};
export const executeCmd=async(cmd,{sg,st,sm_mem,sproj})=>{const TD=getToday(),TM=getMonth(),WS=getWeekStart();try{switch(cmd.type){case"add_goal":{const cur=await db.get("nx_g",{daily:[],weekly:[],monthly:[]});const sec=cmd.section||"daily";const base={id:uid(),text:cmd.text,done:false};const extra=sec==="daily"?{date:TD}:sec==="weekly"?{weekStart:WS}:{month:TM};const upd={...cur,[sec]:[...(cur[sec]||[]),{...base,...extra}]};await db.set("nx_g",upd);sg(upd);return `Задача: "${cmd.text}"`;}case"complete_goal":{const cur=await db.get("nx_g",{daily:[],weekly:[],monthly:[]});const sec=cmd.section||"daily";const g=(cur[sec]||[]).find(g=>g.id===cmd.goal_id);const upd={...cur,[sec]:(cur[sec]||[]).map(g=>g.id===cmd.goal_id?{...g,done:true}:g)};await db.set("nx_g",upd);sg(upd);return `Выполнено: "${g?.text||cmd.goal_id}"`;}case"add_transaction":{const cur=await db.get("nx_t",[]);const cat=CAT_MAP[cmd.category]||`❓ ${cmd.category}`;const tx={id:uid(),type:cmd.tx_type||"expense",amount:Number(cmd.amount),category:cat,description:cmd.description,date:TD,walletId:cmd.walletId||null,status:"charged"};const upd=[...cur,tx];await db.set("nx_t",upd);st(upd);return `Транзакция: ${tx.type==="income"?"+":"-"}₪${cmd.amount}`;}case"add_project_task":{const cur=await db.get("nx_projects",[]);const proj=cur.find(p=>p.id===cmd.project_id||p.name.toLowerCase().includes((cmd.project_name||"").toLowerCase()));if(!proj)return"Проект не найден";const task={id:uid(),text:cmd.text,done:false,createdAt:Date.now()};const upd=cur.map(p=>p.id===proj.id?{...p,tasks:[...(p.tasks||[]),task]}:p);await db.set("nx_projects",upd);sproj(upd);return `Задача в "${proj.name}"`;}case"save_memory":{const cur=await db.get("nx_mem",[]);const upd=[...cur,{text:cmd.memory,ts:Date.now()}].slice(-30);await db.set("nx_mem",upd);sm_mem(upd);return `Запомнил: "${cmd.memory}"`;}default:return null;}}catch{return null;}};
export const Card=({children,s,glow,onClick})=><div onClick={onClick} style={{background:C.card,borderRadius:12,padding:14,border:`1px solid ${glow?C.hi:C.border}`,boxShadow:glow?"0 0 20px rgba(0,212,255,0.07)":undefined,cursor:onClick?"pointer":undefined,transition:"all 0.2s",...s}}>{children}</div>;
export const Lbl=({children,color=C.cyan,mb=8})=><div style={{fontSize:10,fontWeight:800,letterSpacing:2.5,textTransform:"uppercase",color,marginBottom:mb}}>{children}</div>;
export const PBtn=({children,onClick,disabled,s,color})=><button onClick={onClick} disabled={disabled} style={{background:disabled?C.dim:color||"linear-gradient(135deg,#0055cc,#00d4ff)",color:"#fff",border:"none",padding:"9px 16px",borderRadius:8,fontWeight:700,fontSize:13,cursor:disabled?"default":"pointer",fontFamily:"inherit",transition:"all 0.15s",transform:"scale(1)",...s}}>{children}</button>;
export const GBtn=({children,onClick,s,active,color})=><button onClick={onClick} style={{background:active?`${color||C.cyan}18`:"transparent",border:`1px solid ${active?(color||C.cyan):C.border}`,color:active?(color||C.cyan):C.muted,padding:"7px 14px",borderRadius:8,fontSize:12,cursor:"pointer",fontFamily:"inherit",transition:"all 0.15s",...s}}>{children}</button>;
export const Inp=({val,set,ph,type="text",onKD,s,rows})=>rows?<textarea value={val} onChange={e=>set(e.target.value)} placeholder={ph} onKeyDown={onKD} rows={rows} style={{background:C.card2,border:`1px solid ${C.border}`,color:C.text,borderRadius:8,padding:"9px 12px",fontFamily:"inherit",fontSize:13,outline:"none",width:"100%",resize:"none",lineHeight:1.5,...s}}/>:<input value={val} onChange={e=>set(e.target.value)} placeholder={ph} type={type} onKeyDown={onKD} style={{background:C.card2,border:`1px solid ${C.border}`,color:C.text,borderRadius:8,padding:"9px 12px",fontFamily:"inherit",fontSize:13,outline:"none",width:"100%",...s}}/>;
export const Sel=({val,set,children,s})=><select value={val} onChange={e=>set(e.target.value)} style={{background:C.card2,border:`1px solid ${C.border}`,color:C.text,borderRadius:8,padding:"9px 12px",fontFamily:"inherit",fontSize:13,outline:"none",width:"100%",...s}}>{children}</select>;
export const Chip=({children,active,onClick,color=C.cyan})=><button onClick={onClick} style={{padding:"4px 10px",borderRadius:20,border:`1px solid ${active?color:C.border}`,background:active?`${color}18`:"transparent",color:active?color:C.muted,fontSize:11,cursor:"pointer",fontFamily:"inherit",fontWeight:active?700:400}}>{children}</button>;
export function Confetti({onDone}){const pieces=Array.from({length:40},(_,i)=>({id:i,x:Math.random()*100,delay:Math.random()*.8,dur:1+Math.random()*1.5,color:["#00d4ff","#10b981","#f59e0b","#8b5cf6","#ef4444","#ec4899"][i%6],shape:i%3===0?"circle":i%3===1?"rect":"tri"}));useEffect(()=>{const t=setTimeout(onDone,2800);return()=>clearTimeout(t);},[]);return <div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:9999,overflow:"hidden"}}>{pieces.map(p=><div key={p.id} style={{position:"absolute",left:`${p.x}%`,top:-20,width:p.shape==="circle"?8:7,height:p.shape==="circle"?8:p.shape==="rect"?12:8,background:p.color,borderRadius:p.shape==="circle"?"50%":2,animation:`cffall ${p.dur}s ${p.delay}s forwards ease-in`,clipPath:p.shape==="tri"?"polygon(50% 0%,0% 100%,100% 100%)":"none"}}/>)}</div>;}
export const Skel=({w="100%",h=14,r=6,mb=0})=><div style={{width:w,height:h,borderRadius:r,background:C.dim,marginBottom:mb,animation:"shimmer 1.5s infinite linear"}}/>;
export function GStyles(){return <style>{`*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:3px}::-webkit-scrollbar-track{background:#050a14}::-webkit-scrollbar-thumb{background:rgba(0,212,255,.2);border-radius:2px}select option{background:#080e1c;color:#c8d8e8}@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}@keyframes pop{0%{transform:scale(1)}40%{transform:scale(1.35)}100%{transform:scale(1)}}@keyframes slideIn{from{opacity:0;transform:translateX(18px)}to{opacity:1;transform:none}}@keyframes cffall{0%{transform:translateY(0) rotate(0);opacity:1}100%{transform:translateY(110vh) rotate(720deg);opacity:0}}@keyframes shimmer{0%{opacity:.45}50%{opacity:.9}100%{opacity:.45}}@keyframes glow-ring{0%,100%{filter:drop-shadow(0 0 2px #10b981)}50%{filter:drop-shadow(0 0 8px #10b981)}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}@keyframes tada{0%{transform:scale(1)}50%{transform:scale(1.1)}100%{transform:scale(1)}}.fu{animation:fadeUp .25s ease}.pop{animation:pop .4s ease}.si{animation:slideIn .2s ease}`}</style>}
export function TopBar({now,theme,setTheme}){const[t,setT]=useState("");useEffect(()=>{const tick=()=>setT(new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);const curTheme=THEMES.find(x=>x.id===theme)||THEMES[0];const nextTheme=()=>{const i=THEMES.findIndex(x=>x.id===theme);setTheme(THEMES[(i+1)%THEMES.length].id)};return <header style={{background:"rgba(5,10,20,.98)",borderBottom:`1px solid ${C.border}`,padding:"10px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",flexShrink:0}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:32,height:32,background:"linear-gradient(135deg,#0044bb,#00d4ff)",borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontWeight:900,fontSize:14,color:"#fff",fontFamily:"monospace"}}>N</span></div><div><div style={{fontSize:11,fontWeight:800,color:C.cyan,letterSpacing:3}}>NEXUS</div><div style={{fontSize:9,color:C.muted}}>{now.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}</div></div></div><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={nextTheme} style={{background:"transparent",border:`1px solid ${C.border}`,borderRadius:8,padding:"4px 9px",fontSize:13}}>{curTheme.icon}</button><div style={{fontFamily:"monospace",fontSize:17,color:C.cyan,fontWeight:700,letterSpacing:2}}>{t}</div></div></header>}
export function NavBar({tab,setTab}){const nav=[{id:"dash",icon:"◈",label:"Главная"},{id:"finance",icon:"◎",label:"Финансы"},{id:"ai",icon:"⬡",label:"NEXUS AI"}];return <nav style={{flexShrink:0,background:"rgba(5,10,20,.98)",borderTop:`1px solid ${C.border}`,display:"flex"}}>{nav.map(it=><button key={it.id} onClick={()=>setTab(it.id)} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:2,padding:"10px 0 8px",background:"none",border:"none",color:tab===it.id?C.cyan:C.muted,fontSize:10,cursor:"pointer",position:"relative"}}><span style={{fontSize:20}}>{it.icon}</span><span>{it.label}</span>{tab===it.id&&<div style={{position:"absolute",bottom:0,width:24,height:2,background:C.cyan}}/>}</button>)}</nav>}
export function DrillBlock({icon,label,value,sub,color,onClick,pulse}){return <div onClick={onClick} style={{background:C.card,borderRadius:12,padding:"12px 14px",border:`1px solid ${C.border}`,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:18,animation:pulse?"tada .8s":"none"}}>{icon}</span><span style={{color}}>→</span></div><div style={{fontSize:21,fontWeight:900,color,fontFamily:"monospace"}}>{value}</div><div style={{fontSize:9,color:C.muted,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:9,color}}>{sub}</div></div>}
